// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/register/api/data_source_impl/register_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/features/register/api/client/register_api.dart'
    as _i3;
import 'package:online_exam_app/features/register/api/model/register_response.dart'
    as _i2;
import 'package:online_exam_app/features/register/data/model/register_request.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponse_0 extends _i1.SmartFake
    implements _i2.RegisterResponse {
  _FakeRegisterResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterApi extends _i1.Mock implements _i3.RegisterApi {
  MockRegisterApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RegisterResponse> register({
    required _i5.RegisterRequest? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {#body: body}),
            returnValue: _i4.Future<_i2.RegisterResponse>.value(
              _FakeRegisterResponse_0(
                this,
                Invocation.method(#register, [], {#body: body}),
              ),
            ),
          )
          as _i4.Future<_i2.RegisterResponse>);
}
