// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/register/data/repos_impl/register_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:online_exam_app/core/api_rasult/api_result.dart' as _i6;
import 'package:online_exam_app/core/cache/storage_source.dart' as _i3;
import 'package:online_exam_app/features/register/api/client/register_api.dart'
    as _i2;
import 'package:online_exam_app/features/register/api/data_source_impl/register_remote_data_source_impl.dart'
    as _i4;
import 'package:online_exam_app/features/register/domain/entities/user_entity.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterApi_0 extends _i1.SmartFake implements _i2.RegisterApi {
  _FakeRegisterApi_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorageService_1 extends _i1.SmartFake
    implements _i3.SecureStorageService {
  _FakeSecureStorageService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegisterRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterRemoteDataSourceImpl extends _i1.Mock
    implements _i4.RegisterRemoteDataSourceImpl {
  MockRegisterRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RegisterApi get registerApi =>
      (super.noSuchMethod(
            Invocation.getter(#registerApi),
            returnValue: _FakeRegisterApi_0(
              this,
              Invocation.getter(#registerApi),
            ),
          )
          as _i2.RegisterApi);

  @override
  _i3.SecureStorageService get secureStorageService =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorageService),
            returnValue: _FakeSecureStorageService_1(
              this,
              Invocation.getter(#secureStorageService),
            ),
          )
          as _i3.SecureStorageService);

  @override
  set registerApi(_i2.RegisterApi? _registerApi) => super.noSuchMethod(
    Invocation.setter(#registerApi, _registerApi),
    returnValueForMissingStub: null,
  );

  @override
  set secureStorageService(_i3.SecureStorageService? _secureStorageService) =>
      super.noSuchMethod(
        Invocation.setter(#secureStorageService, _secureStorageService),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i6.ApiResult<_i7.RegisterEntity>> register(
    String? username,
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              username,
              firstName,
              lastName,
              email,
              password,
              rePassword,
              phone,
            ]),
            returnValue: _i5.Future<_i6.ApiResult<_i7.RegisterEntity>>.value(
              _i8.dummyValue<_i6.ApiResult<_i7.RegisterEntity>>(
                this,
                Invocation.method(#register, [
                  username,
                  firstName,
                  lastName,
                  email,
                  password,
                  rePassword,
                  phone,
                ]),
              ),
            ),
          )
          as _i5.Future<_i6.ApiResult<_i7.RegisterEntity>>);
}
