// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/question/api/data_source_impl/get_questions_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/features/question/api/client/question_api.dart'
    as _i3;
import 'package:online_exam_app/features/question/api/models/questions_response.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuestionsResponse_0 extends _i1.SmartFake
    implements _i2.QuestionsResponse {
  _FakeQuestionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QuestionApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionApi extends _i1.Mock implements _i3.QuestionApi {
  MockQuestionApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.QuestionsResponse> getQuestionById(String? examtId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionById, [examtId]),
            returnValue: _i4.Future<_i2.QuestionsResponse>.value(
              _FakeQuestionsResponse_0(
                this,
                Invocation.method(#getQuestionById, [examtId]),
              ),
            ),
          )
          as _i4.Future<_i2.QuestionsResponse>);
}
