// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/exams/presentation/cubit/exams_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam_app/core/api_rasult/api_result.dart' as _i5;
import 'package:online_exam_app/features/exams/domain/entities/exams_exntity.dart'
    as _i6;
import 'package:online_exam_app/features/exams/domain/repos/get_exams_repo.dart'
    as _i2;
import 'package:online_exam_app/features/exams/domain/usecases/get_exams_user_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetExamsRepo_0 extends _i1.SmartFake implements _i2.GetExamsRepo {
  _FakeGetExamsRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetExamsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExamsUseCase extends _i1.Mock implements _i3.GetExamsUseCase {
  MockGetExamsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetExamsRepo get getExamsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#getExamsRepo),
            returnValue: _FakeGetExamsRepo_0(
              this,
              Invocation.getter(#getExamsRepo),
            ),
          )
          as _i2.GetExamsRepo);

  @override
  _i4.Future<_i5.ApiResult<List<_i6.ExamsEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.ApiResult<List<_i6.ExamsEntity>>>.value(
              _i7.dummyValue<_i5.ApiResult<List<_i6.ExamsEntity>>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<List<_i6.ExamsEntity>>>);
}
